linters:
  enable:
    - dogsled
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nestif
    - prealloc
    # - unconvert
    - unparam
    - revive

linters-settings:
  # govet:
  #   enable:
  #     - fieldalignment
  revive:
    rules:
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
      - name: var-naming
        severity: warning
        exclude: [""]
        arguments:
          - ["ID"] # AllowList

run:
  timeout: 3m

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G404"
    - linters:
        - funlen
      path: _test\.go
    - linters:
        - errcheck
      path: _test\.go

